export const properties = [
  {
    id: "prop1",
    title: "Modern Studio Apartment",
    location: "Papine, Kingston 6",
    price: 35000,
    bedrooms: 1,
    bathrooms: 1,
    area: 450,
    distance: 0.5,
    image: "/urban-minimalist-living.png",
  },
  {
    id: "prop2",
    title: "Spacious 2-Bedroom House",
    location: "Mona, Kingston 7",
    price: 55000,
    bedrooms: 2,
    bathrooms: 1.5,
    area: 850,
    distance: 1.2,
    image: "/cozy-garden-home.png",
  },
  {
    id: "prop3",
    title: "Cozy 1-Bedroom Apartment",
    location: "Hope Pastures, Kingston 6",
    price: 40000,
    bedrooms: 1,
    bathrooms: 1,
    area: 550,
    distance: 0.8,
    image: "/sunlit-reading-nook.png",
  },
  {
    id: "prop4",
    title: "3-Bedroom Family Home",
    location: "Liguanea, Kingston 6",
    price: 75000,
    bedrooms: 3,
    bathrooms: 2,
    area: 1200,
    distance: 1.5,
    image: "/cozy-family-gathering.png",
  },
  {
    id: "prop5",
    title: "Student Shared Apartment",
    location: "August Town, Kingston 7",
    price: 25000,
    bedrooms: 2,
    bathrooms: 1,
    area: 700,
    distance: 0.3,
    image: "/cozy-shared-living.png",
  },
  {
    id: "prop6",
    title: "Luxury Studio with View",
    location: "Barbican, Kingston 6",
    price: 45000,
    bedrooms: 1,
    bathrooms: 1,
    area: 500,
    distance: 2.0,
    image: "/placeholder.svg?height=500&width=800&query=luxury studio apartment",
  },
  {
    id: "prop7",
    title: "2-Bedroom Townhouse",
    location: "Manor Park, Kingston 8",
    price: 60000,
    bedrooms: 2,
    bathrooms: 2.5,
    area: 950,
    distance: 2.5,
    image: "/placeholder.svg?height=500&width=800&query=townhouse",
  },
  {
    id: "prop8",
    title: "Budget Single Room",
    location: "Papine, Kingston 6",
    price: 18000,
    bedrooms: 1,
    bathrooms: 1,
    area: 300,
    distance: 0.4,
    image: "/placeholder.svg?height=500&width=800&query=single room",
  },
  {
    id: "prop9",
    title: "4-Bedroom Student House",
    location: "Hope Road, Kingston 6",
    price: 90000,
    bedrooms: 4,
    bathrooms: 3,
    area: 1500,
    distance: 1.8,
    image: "/placeholder.svg?height=500&width=800&query=student house",
  },
]
